"""Initial migration

Revision ID: 2530dee41b83
Revises: 
Create Date: 2024-07-31 14:55:18.451698

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2530dee41b83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Hotels',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('location', sa.String(), nullable=False),
        sa.Column('services', sa.JSON(), nullable=True),
        sa.Column('rooms_quantity', sa.Integer(), nullable=False),
        sa.Column('image_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('books')
    op.drop_table('authors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'authors',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('author', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='authors_pkey')
    )
    op.create_table(
        'books',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    op.drop_table('Hotels')
    # ### end Alembic commands ###
