"""Create all tables

Revision ID: 5c4e3322e472
Revises: 2530dee41b83
Create Date: 2024-08-01 09:28:04.173468

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5c4e3322e472'
down_revision: Union[str, None] = '2530dee41b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('room_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'Rooms',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('hotel_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('services', sa.JSON(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('image_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['hotel_id'], ['Hotels.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'Bookings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('room_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date_from', sa.Date(), nullable=False),
        sa.Column('date_to', sa.Date(), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('total_cost', sa.Integer(), sa.Computed('(date_to - date_from) * price', ), nullable=False),
        sa.Column('total_days', sa.Integer(), sa.Computed('date_to - date_from', ), nullable=False),
        sa.ForeignKeyConstraint(['room_id'], ['Rooms.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(
        'Hotels', 'services',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False)
    op.alter_column(
        'Hotels', 'image_id',
        existing_type=sa.INTEGER(),
        nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Hotels', 'image_id',
        existing_type=sa.INTEGER(),
        nullable=True)
    op.alter_column(
        'Hotels', 'services',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True)
    op.drop_table('Bookings')
    op.drop_table('Rooms')
    op.drop_table('Users')
    # ### end Alembic commands ###
