"""Edit few columns

Revision ID: 713405539dbb
Revises: 5c4e3322e472
Create Date: 2024-08-01 09:39:31.383556

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '713405539dbb'
down_revision: Union[str, None] = '5c4e3322e472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Hotels', 'services',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True)
    op.alter_column(
        'Rooms', 'services',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Rooms', 'services',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False)
    op.alter_column(
        'Hotels', 'services',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False)
    # ### end Alembic commands ###
