"""Last migration I hope

Revision ID: ed1f5c14fdcb
Revises: 713405539dbb
Create Date: 2024-08-01 09:44:14.403721

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ed1f5c14fdcb'
down_revision: Union[str, None] = '713405539dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Rooms', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('Users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('Users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('Users', 'user_id')
    op.drop_column('Users', 'room_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Users', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Users', 'hashed_password')
    op.drop_column('Users', 'email')
    op.drop_column('Rooms', 'price')
    # ### end Alembic commands ###